#!/bin/bash
#------------------------------------------------------------
# initd script for running services without start-stop-daemon
# (c) Wolfgang Ziegler, nuppla@zites.net, drunomics GmbH
#------------------------------------------------------------

# Find config file

CONF_FILE=syncd.conf
SYNCD_CONFIG_DIR=$PWD
SCRIPT=`readlink -f $0`
DAEMON_NAME=syncd
LINK=`readlink -f $0`
SCRIPT_DIR=`dirname $LINK`

if [ ! -e $CONF_FILE ]; then
    echo "Unable to find syncd configuration file \"$CONF_FILE\"." 
    echo "Run \"syncd init\" to create a new \"$CONF_FILE\"."
fi

COMMAND="rsync $RSYNC_OPTIONS --exclude=$RSYNC_EXCLUDE --delete $WATCH_DIR/ $SSH_USER@$SSH_HOST:$REMOTE_TARGET_DIR"

case $1 in
    init)
        if [ ! -e $CONF_FILE ] ; then
            wget https://raw.githubusercontent.com/drunomics/syncd/master/syncd.conf
            echo "New file $CONF_FILE created on current folder."
        else
            echo "There is already a $CONF_FILE. Please remove it."
            exit 1
        fi
    ;;

    start)
      if [ -e ${PIDFILE} ] && ( ps -p `cat $PIDFILE` > /dev/null ); then
        echo "$DAEMON_NAME is already running."
        exit 1;
      fi
      export WATCH_EXCLUDE
      export WATCH_VERBOSE
      export WATCH_DIR
      $SCRIPT_DIR/watch.sh $COMMAND >> $LOGFILE &
      echo "$!" > $PIDFILE
      echo "Starting $DAEMON_NAME..."
    ;;

    stop)
      if [ ! -e ${PIDFILE} ] || ( ! ps -p `cat $PIDFILE` > /dev/null ); then
        echo "$DAEMON_NAME is not running."
        exit 1;
      fi

      echo "Stopping $DAEMON_NAME..."
      PID=`cat $PIDFILE`
      CHILD_PIDS=$(pgrep -P $PID);
      kill $PID 2> /dev/null || echo Killing process failed, not running?
      # Wait half a second and Kill child PIDs to be sure they are gone.
      sleep 0.5
      kill $CHILD_PIDS 2> /dev/null
      rm $PIDFILE
    ;;
    restart)
      $SCRIPT stop
      $SCRIPT start
    ;;

    status)
      if [ -e ${PIDFILE} ] && ( ps -p `cat $PIDFILE` > /dev/null ); then
          echo "$DAEMON_NAME is running."
      else
          echo "$DAEMON_NAME is not running."
      fi
    ;;

    run)
      $COMMAND && echo Done.
    ;;

    log)
      tail -f $LOGFILE
    ;;

    *)
      echo "Usage: $0 {init|start|stop|restart|status|run|log}"
      exit 3
    ;;
esac
